"""Initial migration

Revision ID: 86641c7660ef
Revises: 
Create Date: 2025-11-13 13:21:34.050643+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86641c7660ef'
down_revision: str = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email_id', sa.String(length=255), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('inserted_by', sa.String(length=100), nullable=False),
    sa.Column('inserted_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email_id', sa.String(length=255), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('customer_status', sa.Integer(), nullable=False),
    sa.Column('inserted_by', sa.String(length=100), nullable=False),
    sa.Column('inserted_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('otp_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('otp_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('inserted_by', sa.String(length=100), nullable=False),
    sa.Column('inserted_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schemes_details',
    sa.Column('schemes_detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('available_for', sa.String(length=100), nullable=True),
    sa.Column('name_of_the_scheme', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('documents_required', sa.Text(), nullable=True),
    sa.Column('apply_and_link', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('inserted_by', sa.String(length=100), nullable=False),
    sa.Column('inserted_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('schemes_detail_id')
    )
    op.create_table('admin_logins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('inserted_by', sa.String(length=100), nullable=False),
    sa.Column('inserted_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('customer_logins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('inserted_by', sa.String(length=100), nullable=False),
    sa.Column('inserted_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('loan_interest_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.String(length=20), nullable=False),
    sa.Column('tenure_years', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.String(length=50), nullable=True),
    sa.Column('max_amount', sa.String(length=50), nullable=True),
    sa.Column('processing_fee', sa.String(length=50), nullable=True),
    sa.Column('inserted_by', sa.String(length=100), nullable=False),
    sa.Column('inserted_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes_details.schemes_detail_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multilingual_schemes_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name_of_the_scheme', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('documents_required', sa.Text(), nullable=True),
    sa.Column('inserted_by', sa.String(length=100), nullable=False),
    sa.Column('inserted_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes_details.schemes_detail_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multilingual_schemes_data')
    op.drop_table('loan_interest_details')
    op.drop_table('customer_logins')
    op.drop_table('admin_logins')
    op.drop_table('schemes_details')
    op.drop_table('otp_details')
    op.drop_table('customers')
    op.drop_table('admins')
    # ### end Alembic commands ###
